version: '3.8'

services:
  client:
    platform: linux/amd64
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    restart: unless-stopped
    ports:
      - '5173:5173'
    env_file:
      - ./client/.env
    volumes:
      - ./client/:/app
      - /app/node_modules

  server:
    platform: linux/amd64
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    restart: unless-stopped
    ports:
      - '5174:3000'
    env_file:
      - ./server/.env
    volumes:
      - ./server/:/app
